config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', to: 'books#index'

  resources :books, only:[:index, :show, :new, :create, :destroy] do
    resources :reviews, only:[:new, :create]
  end


  resources :authors, only:[:show, :destroy]

  resources :users, only:[:show]

  resources :reviews, only:[:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
   validates_presence_of :name
   has_many :book_authors, dependent: :destroy
   has_many :books, through: :book_authors


end

app/models/book.rb
class Book < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :pages
  validates_presence_of :year
  validates_presence_of :image_url

  has_many :reviews
  has_many :book_authors, dependent: :destroy
  has_many :authors, through: :book_authors

  def self.get_by_reviews(order)
   joins(:reviews).order("reviews.score #{order}").limit(3)
  end

  def self.sort_by_book(order = :asc)
    Book.order(pages: order)
  end

  def self.sort_by_average_rating(order = :asc)
      Book.joins(:reviews)
      .select("books.*, avg(reviews.score) as rating")
      .order("rating #{order}")
      .group(:id)
  end

  def self.sort_by_total_scores(order = :asc)
      Book.joins(:reviews)
      .select("books.*, count(reviews) as count ")
      .order("count #{order}")
      .group(:id)
  end






end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/review.rb
class Review < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :description
  validates_presence_of :score
  belongs_to :book
  belongs_to :user


  def self.top_three
    Review.order(score: :desc).limit(3)
  end

  def self.bottom_three
    Review.order(score: :asc).limit(3)
  end

  def self.average_score
    Review.average(:score)
  end

  def self.top_review
    Review.order(score: :desc).limit(1).first
  end

end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name
  has_many :reviews

  def sort_by_review_age(order = :asc)
    reviews.order(created_at: order)
  end

  def self.top_users_with_the_most_reviews
    User.joins(:reviews)
    .select("users.*, count(reviews) as count")
    .order('count desc')
    .group(:id)
    .limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception  
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def show
    @author = Author.find(params[:id])
  end

  def destroy
    @author = Author.find(params[:id])
    author_id = @author.id
    book_authors = BookAuthor.where(author_id: params[:id])
    BookAuthor.delete(book_authors)
    @books = @author.books

    @books.each do |book|
      book.reviews.each do |review|
        Review.delete(review.id)
      end
      Book.delete(params[book.id])
    end
    
    Author.delete(@author.id)

    redirect_to books_path
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    if params[:column] == 'rating' && params[:order] == 'asc'
      @books = Book.sort_by_average_rating
    elsif params[:column] == 'rating' && params[:order] == 'desc'
      @books = Book.sort_by_average_rating(:desc)
    elsif params[:column] == 'pages' && params[:order] == 'asc'
      @books = Book.sort_by_book
    elsif params[:column] == 'pages' && params[:order] == 'desc'
      @books = Book.sort_by_book(:desc)
    elsif params[:column] == 'reviews' && params[:order] == 'asc'
      @books = Book.sort_by_total_scores
    elsif params[:column] == 'reviews' && params[:order] == 'desc'
      @books = Book.sort_by_total_scores(:desc)
    else
      @books = Book.all
    end

    
    @top_books = Book.get_by_reviews(:desc)
    @worst_books =  Book.get_by_reviews(:asc)
    @most = User.top_users_with_the_most_reviews

  end

  def show
    @book = Book.find(params[:id])
    @top_three_reviews = @book.reviews.top_three
    @bottom_three_reviews = @book.reviews.bottom_three
    @average_score = @book.reviews.average_score
  end

  def new
    @book = Book.new
  end

  def create
    book = Book.create(book_params)
    authors = author_params[:name].split(",")
    authors.each do |author|
      book.authors.create(name: author)
    end
    redirect_to book_path(book.id)
  end

  def destroy
    book_authors = BookAuthor.where(book_id: params[:id])
    BookAuthor.delete(book_authors)
    reviews = Review.where(book_id: params[:id])
    Review.delete(reviews)
    Book.delete(params[:id])
    redirect_to books_path
  end

  private

  def book_params
    retianed_params = params.require(:book).permit(:title, :year, :pages, :image_url, :authors)
    {title: retianed_params[:title].titlecase, year: retianed_params[:year], pages: retianed_params[:pages], image_url: retianed_params[:image_url]}
  end

  def author_params
    retianed_params = params.require(:book).permit(:authors)
    {name: retianed_params[:authors].titlecase}
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @book = Book.find(params[:book_id])
  end

  def show
    @review = Review.find(params[:id])
  end

  def destroy
    @review = Review.find(params[:id])
    user_id = @review.user_id
    @review.destroy
    redirect_to user_path(user_id)
  end

  def create
    book = Book.find(params[:book_id])
      if User.find_by(name: params[:review][:user]) == nil
      user = User.find_or_create_by(name: params[:review][:user].titlecase)
      hash = review_params
      hash[:user_id]= user[:id]
      review = book.reviews.create(hash)

      redirect_to book_path(review.book_id)
      else
      redirect_to new_book_review_path(book)
      end
  end

  private

  def review_params
    rp = params.require(:review).permit(:title, :description, :score, :user)
    {title: rp[:title], description: rp[:description], score: rp[:score]}
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    if params[:sort] == 'asc'
    @reviews = @user.sort_by_review_age
    elsif params[:sort] == 'desc'
    @reviews = @user.sort_by_review_age(:desc)
    else
    @reviews = @user.reviews
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/show.html.erb
<html>
<head> <LINK rel="stylesheet" href="authors_show.css"> </head>

<div class='show_page'>
<div class='title'> <h1><%= @author.name %> </h1></div>

<div class='author_info'>
    <ul>
    <% @author.books.each do |book| %>
    <li><%=link_to(book.title, book_path(book)) %><br></li>
    <li><%= book.year %><br></li>
    <li><%= book.pages %><br></li>
    <li><%= book.reviews.top_review.title %><br></li>
    <li><%= book.reviews.top_review.score %><br></li>
    <li><%= link_to(book.reviews.top_review.user.name, user_path(book.reviews.top_review.user)) %><br></li>
    <% end %>
  </ul>
</div>

<div class='delete_button'> <%= button_to "Delete", author_path(@author.id), method: :delete %></div>
</div>
</html>

app/views/books/index.html.erb
<html>
<head> <LINK rel="stylesheet" href="books_index.css"></head>

  <div class="Sortby">
    <h1> Sort Books by </h1>
    <p><%= link_to"Average Rating Ascending", books_path(column: 'rating', order: 'asc') %></p>
    <p><%= link_to"Average Rating Descending", books_path(column: 'rating', order: 'desc') %></p>
    <p><%= link_to"Average Number of Pages Ascending", books_path(column: 'pages', order: 'asc') %></p>
    <p><%= link_to"Average Number of Pages Descending", books_path(column: 'pages', order: 'desc') %></p>
    <p><%= link_to"Average Number of Reviews Ascending", books_path(column: 'reviews', order: 'asc') %></p>
    <p><%= link_to"Average Number of Reviews Descending", books_path(column: 'reviews', order: 'desc') %></p>
  </div>
  
<ul class="stats">
  <div id="highest">
    <h1>Highest Rated Books</h1>
      <% @top_books.each do |book| %>
      <li><%=link_to(book.title, book_path(book)) %> Score: <%= book.reviews.average_score.round %></li>
      <% end %>
  </div>

  <div id="worst">
    <h1> Worst Books </h1>
      <% @worst_books.each do |book| %>
      <li><%=link_to(book.title, book_path(book)) %> Score: <%= book.reviews.average_score.round %></li>
      <% end %>
  </div>

  <div id="most_reviews">
   <h1> Most Reviews </h1>
      <% @most.each do |user| %>
      <li><%= link_to(user.name, user_path(user)) %> <%= user.reviews.count %> </li>
      <% end %>
  </div>
</ul>



  <div class="all_books">
      <% @books.each do |book| %>
      <div class='each_book'><h1><%= link_to("#{book.title}", book_path(book)) %></h1>
           <% book.authors.each do |author| %>
           <p>Author: <%= link_to("#{author.name}", author_path(author.id)) %> </p>
            <% end %>
      <p> Length: <%= book.pages %> </p>
      <p> Average Rating: <%= book.reviews.average_score%></p>
      <p> Total Reviews: <%= book.reviews.count %></p></div>
      <% end %>
  </div>


</html>

app/views/books/new.html.erb
<html>
<head>
<LINK href="books_new.css" rel="stylesheet" type="text/css"/>
</head>

  <div class="title"><h1> Create A New Book </h1></div>

    <div class="form">
      <%= form_for @book do |f| %>

      <div class="title_field"><%= f.label :title %>
      <%= f.text_field :title %></div>

      <div class="year_field"><%= f.label :year %>
      <%= f.text_field :year %></div>

      <div class="pages_field"><%= f.label :pages %>
      <%= f.text_field :pages %></div>

      <div class="authors_field"><%= f.label :authors %>
      <%= f.text_field :authors, :value => "" %></div>

      <div class="img_url_field"><%= f.label :image_url %>
      <%= f.text_field :image_url %></div>

      <div class="submit_button"><%= f.submit %></div>

      <% end %>
    </div>

</html>

app/views/books/show.html.erb
<html>
<head>
   <LINK rel="stylesheet" href="books_show.css" type="text/css"/>
 </head>

<div class="book">
  <h1>Title: <%= @book.title %></h1>
  <% @book.authors.each do |author| %>
  <p>Author: <%= link_to(author.name, author_path(author)) %></p>
  <% end %>
  <p>Length: <%= @book.pages %> Pages</p>
</div>
  <%= button_to "Delete",book_path(@book.id), method: :delete %>


<div class="reviews_title"><h1> Reviews </h1></div>

<div class="review">
  <% if !@book.reviews.empty? %>
    <% @book.reviews.each do |review| %>
      <p>Title:<%= review.title %></p>
      <p>Description:<%= review.description %></p>
      <p> <%= link_to "#{review.user.name}", user_path(review.user.id) %></p>
      <p>Score:<%= review.score %> Stars</p><br><br>
    <% end %>
  <% end %>
</div>

<div class='book_stats'>
  <p>Top Three</p>
  <div class='top_three'><% @top_three_reviews.each do |review| %>
  <%= review.title %>
  <%= review.description %>
  <%= review.score %><br><br>
  <% end %>
</div>

  <div class='bottom_three'><p>Bottom Three</p>
  <% @bottom_three_reviews.each do |review| %>
  <%= review.title %>
  <%= review.description %>
  <%= review.score %><br><br>
  <% end %>
</div>

  <div class='avg_score'>
  <p>Average Score: <%= @average_score %></p>
 </div>
</div>

<div class='create_a_review'>
  <p><%= link_to("Create Review", new_book_review_path(@book.id))%></p>
</div>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookClub</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <navbar>
      <p><%= link_to("Home","/") %></p>
      <p><%= link_to("Books",books_path) %></p>
      <p><%= link_to("Create A New Book",new_book_path(@book)) %></p>


    </navbar>
    <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<div class='title'><h1>Create a Review</h1></div>
<div class='form'><%= form_for [@book, @review] do |f| %>
<div class='title_field'><%= f.label :title %>
  <%= f.text_field :title %></div>

<div class='description_field'><%= f.label :description %>
  <%= f.text_field :description %></div>

<div class='score_field'><%= f.label :score %>
  <%= f.text_field :score %></div>

<div class='user_field'><%= f.label :user %>
  <%= f.text_field :user %></div>

<div class='submit_button'><%= f.submit %></div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class='title'><h1><%=@user.name %></h1></div>
<p><%= link_to"Newest Reviews", user_path(sort: 'desc') %></p>
<p><%= link_to"Oldest Reviews", user_path(sort: 'asc') %></p>

<div Class="users" id="User-<%="#{@user.name}"%>">
<% @reviews.each do |review| %>
  <li><h2><%= review.title %></h2></li>
  <li><p><%=link_to(review.book.title, book_path(review.book)) %></p></li>
  <li><p>Rating: <%= review.score %> Stars</p></li>
  <li><p><%= review.description %></p><br></li>
  <li><%= button_to "Delete",review_path(review), method: :delete %></li>
<% end %>
</ul>
</div>